# Dockerfile.dev
FROM ruby:3.2

# Install system dependencies
RUN apt-get update -qq && \
    apt-get install -y build-essential libpq-dev nodejs npm postgresql-client && \
    npm install -g yarn

# Create app directory
WORKDIR /app

# Install gems
COPY Gemfile Gemfile.lock ./
RUN gem install bundler && bundle install

# Install JS dependencies
COPY package.json yarn.lock ./
RUN yarn install

# Copy app code
COPY . .

# Expose Rails dev port
EXPOSE 3000

# Run Rails server in dev mode
CMD ["bin/rails", "server", "-b", "0.0.0.0", "-p", "3000"]
